/*
    File: fn_menu_getItemCardControls.sqf
    Author: Legend
    Description: Returns the fixed two-column item-card control pool used by
        the local Browser and Configure presentation renderers.
    Execution: Client
    Parameters:
        None
    Returns:
        Item-card control IDC groups <ARRAY<ARRAY<NUMBER>>>
    Public: No
*/

#include "..\..\..\ui\menu\idcs.hpp"

[
    [
        BN_KOTH_IDC_MENU_BROWSER_CARD_1_BG,
        BN_KOTH_IDC_MENU_BROWSER_CARD_1_IMAGE_AREA,
        BN_KOTH_IDC_MENU_BROWSER_CARD_1_IMAGE,
        BN_KOTH_IDC_MENU_BROWSER_CARD_1_NAME,
        BN_KOTH_IDC_MENU_BROWSER_CARD_1_STATUS,
        BN_KOTH_IDC_MENU_BROWSER_CARD_1_LOCK_OVERLAY,
        BN_KOTH_IDC_MENU_BROWSER_CARD_1_LOCK_TEXT,
        BN_KOTH_IDC_MENU_BROWSER_CARD_1_PRIMARY_ACTION,
        BN_KOTH_IDC_MENU_BROWSER_CARD_1_SECONDARY_ACTION
    ],
    [
        BN_KOTH_IDC_MENU_BROWSER_CARD_2_BG,
        BN_KOTH_IDC_MENU_BROWSER_CARD_2_IMAGE_AREA,
        BN_KOTH_IDC_MENU_BROWSER_CARD_2_IMAGE,
        BN_KOTH_IDC_MENU_BROWSER_CARD_2_NAME,
        BN_KOTH_IDC_MENU_BROWSER_CARD_2_STATUS,
        BN_KOTH_IDC_MENU_BROWSER_CARD_2_LOCK_OVERLAY,
        BN_KOTH_IDC_MENU_BROWSER_CARD_2_LOCK_TEXT,
        BN_KOTH_IDC_MENU_BROWSER_CARD_2_PRIMARY_ACTION,
        BN_KOTH_IDC_MENU_BROWSER_CARD_2_SECONDARY_ACTION
    ],
    [
        BN_KOTH_IDC_MENU_BROWSER_CARD_3_BG,
        BN_KOTH_IDC_MENU_BROWSER_CARD_3_IMAGE_AREA,
        BN_KOTH_IDC_MENU_BROWSER_CARD_3_IMAGE,
        BN_KOTH_IDC_MENU_BROWSER_CARD_3_NAME,
        BN_KOTH_IDC_MENU_BROWSER_CARD_3_STATUS,
        BN_KOTH_IDC_MENU_BROWSER_CARD_3_LOCK_OVERLAY,
        BN_KOTH_IDC_MENU_BROWSER_CARD_3_LOCK_TEXT,
        BN_KOTH_IDC_MENU_BROWSER_CARD_3_PRIMARY_ACTION,
        BN_KOTH_IDC_MENU_BROWSER_CARD_3_SECONDARY_ACTION
    ],
    [
        BN_KOTH_IDC_MENU_BROWSER_CARD_4_BG,
        BN_KOTH_IDC_MENU_BROWSER_CARD_4_IMAGE_AREA,
        BN_KOTH_IDC_MENU_BROWSER_CARD_4_IMAGE,
        BN_KOTH_IDC_MENU_BROWSER_CARD_4_NAME,
        BN_KOTH_IDC_MENU_BROWSER_CARD_4_STATUS,
        BN_KOTH_IDC_MENU_BROWSER_CARD_4_LOCK_OVERLAY,
        BN_KOTH_IDC_MENU_BROWSER_CARD_4_LOCK_TEXT,
        BN_KOTH_IDC_MENU_BROWSER_CARD_4_PRIMARY_ACTION,
        BN_KOTH_IDC_MENU_BROWSER_CARD_4_SECONDARY_ACTION
    ]
]