/*
    Author: Legend

    Static one-time KOTH wearable policy curated from
    data/wearable_inventory.csv. Facts remain in the CSV; this file owns
    human-authored allowedSides, appearanceSide, and provisional minLevel.
*/

class vn_b_pack_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_pack_01_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_pack_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_pack_02_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_pack_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_pack_03_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_pack_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_pack_04_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_pack_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_pack_05_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_pack_arvn_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_pack_arvn_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_pack_arvn_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_pack_arvn_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_pack_ba18_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_pack_ba22_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_pack_lw_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_pack_lw_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_pack_lw_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_pack_lw_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_pack_lw_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_pack_lw_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_pack_lw_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_pack_m41_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_pack_m41_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_pack_m41_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_pack_m41_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_pack_m41_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_pack_m5_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_pack_p08_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_pack_p08_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_pack_p08_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_pack_p44_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_pack_p44_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_pack_p44_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_pack_pfield_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_pack_pfield_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_pack_prc77_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_pack_seal_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_pack_t10_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_pack_trp_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_pack_trp_01_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_pack_trp_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_pack_trp_02_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_pack_trp_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_pack_trp_03_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_pack_trp_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_pack_trp_04_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_o_pack_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_pack_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_pack_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_pack_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_pack_05 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_pack_06 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_pack_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_pack_08 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_pack_t884_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 45;};
class vn_b_bandana_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_bandana_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_bandana_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_bandana_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_bandana_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_bandana_06 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_bandana_07 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_bandana_08 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_beret_01_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_beret_01_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_beret_01_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_beret_01_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_beret_01_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_beret_01_06 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_beret_01_07 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_beret_01_08 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_beret_01_09 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_beret_01_10 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_beret_01_11 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_beret_03_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_beret_04_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_boonie_01_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_boonie_01_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_boonie_01_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_boonie_01_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_boonie_01_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_boonie_01_06 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_boonie_01_07 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_boonie_01_08 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_boonie_01_09 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_boonie_02_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_boonie_02_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_boonie_02_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_boonie_02_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_boonie_02_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_boonie_02_06 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_boonie_02_07 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_boonie_02_08 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_boonie_02_09 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_boonie_03_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_boonie_03_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_boonie_03_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_boonie_03_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_boonie_03_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_boonie_03_06 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_boonie_03_07 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_boonie_03_08 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_boonie_03_09 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_boonie_04_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_boonie_04_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_boonie_04_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_boonie_04_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_boonie_04_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_boonie_04_06 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_boonie_04_07 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_boonie_04_08 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_boonie_04_09 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_boonie_05_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_boonie_05_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_boonie_05_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_boonie_05_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_boonie_05_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_boonie_05_06 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_boonie_05_07 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_boonie_05_08 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_boonie_05_09 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_boonie_06_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_boonie_06_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_boonie_07_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_boonie_07_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_boonie_08_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_boonie_08_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_boonie_09_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_boonie_09_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_boonie_09_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_boonie_09_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_boonie_09_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_boonie_09_06 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_boonie_09_07 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_boonie_09_08 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_boonie_09_09 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_headband_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_headband_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_headband_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_headband_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_headband_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_headband_08 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_helmet_aph6_01_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_helmet_aph6_01_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_helmet_aph6_01_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_helmet_aph6_01_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_helmet_aph6_01_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_helmet_aph6_02_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_helmet_aph6_02_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_helmet_aph6_02_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_helmet_aph6_02_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_helmet_aph6_02_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_helmet_m1_01_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_helmet_m1_01_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_helmet_m1_02_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_helmet_m1_02_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_helmet_m1_03_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_helmet_m1_03_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_helmet_m1_04_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_helmet_m1_04_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_helmet_m1_05_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_helmet_m1_05_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_helmet_m1_06_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_helmet_m1_06_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_helmet_m1_07_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_helmet_m1_07_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_helmet_m1_08_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_helmet_m1_08_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_helmet_m1_09_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_helmet_m1_09_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_helmet_m1_10_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_helmet_m1_11_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_helmet_m1_12_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_helmet_m1_12_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_helmet_m1_14_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_helmet_m1_14_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_helmet_m1_15_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_helmet_m1_15_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_helmet_m1_16_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_helmet_m1_16_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_helmet_m1_17_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_helmet_m1_17_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_helmet_m1_18_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_helmet_m1_18_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_helmet_m1_19_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_helmet_m1_19_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_helmet_m1_20_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_helmet_m1_20_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_helmet_sog_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_helmet_svh4_01_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_helmet_svh4_01_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_helmet_svh4_01_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_helmet_svh4_01_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_helmet_svh4_01_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_helmet_svh4_01_06 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_helmet_svh4_02_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_helmet_svh4_02_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_helmet_svh4_02_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_helmet_svh4_02_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_helmet_svh4_02_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_helmet_svh4_02_06 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_b_helmet_t56_01_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_b_helmet_t56_01_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_b_helmet_t56_01_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_helmet_t56_02_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_b_helmet_t56_02_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_b_helmet_t56_02_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_c_conehat_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_c_conehat_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_c_headband_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_c_headband_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_c_headband_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_c_headband_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_i_beret_01_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_i_beret_03_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_i_beret_03_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_i_beret_03_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_i_beret_03_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_i_helmet_m1_01_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_i_helmet_m1_01_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_i_helmet_m1_02_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_i_helmet_m1_02_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_i_helmet_m1_03_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_i_helmet_m1_03_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_o_boonie_nva_02_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_o_boonie_nva_02_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_o_boonie_vc_01_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_o_boonie_vc_01_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_o_boonie_vc_02_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_o_boonie_vc_02_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_o_cap_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_o_cap_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_o_cap_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_o_cap_navy_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_o_helmet_nva_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_o_helmet_nva_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_o_helmet_nva_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_o_helmet_nva_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_o_helmet_nva_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_o_helmet_nva_06 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_o_helmet_nva_07 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_o_helmet_nva_08 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_o_helmet_nva_09 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_o_helmet_nva_10 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_o_helmet_shl61_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_o_helmet_shl61_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_o_helmet_tsh3_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_o_helmet_tsh3_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_o_helmet_vc_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_o_helmet_vc_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_o_helmet_vc_03 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_o_helmet_vc_04 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_o_helmet_vc_05 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 30;};
class vn_o_helmet_zsh3_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 5;};
class vn_o_helmet_zsh3_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 10;};
class vn_o_pl_cap_01_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 15;};
class vn_o_pl_cap_02_01 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 20;};
class vn_o_pl_cap_02_02 {allowedSides[] = {"WEST", "EAST"}; appearanceSide = "BOTH"; minLevel = 25;};
class vn_b_uniform_aus_01_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 1;};
class vn_b_uniform_aus_02_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_aus_03_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_aus_04_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_aus_05_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_aus_06_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_aus_07_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_aus_08_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_aus_09_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_aus_10_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_heli_01_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_k2b_01_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_k2b_01_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_k2b_01_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_k2b_01_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_k2b_02_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_k2b_02_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_k2b_02_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_k2b_02_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_k2b_02_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_k2b_03_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_k2b_03_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_macv_01_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_macv_01_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_macv_01_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_macv_01_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_macv_01_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_macv_01_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_macv_01_08 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_macv_01_15 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_macv_01_18 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_macv_01_22 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_macv_01_23 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_macv_01_24 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_macv_01_25 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_macv_01_26 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_macv_02_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_macv_02_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_macv_02_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_macv_02_08 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_macv_02_15 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_macv_02_18 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_macv_03_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_macv_03_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_macv_03_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_macv_03_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_macv_03_08 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_macv_03_15 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_macv_03_18 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_macv_04_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_macv_04_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_macv_04_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_macv_04_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_macv_04_08 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_macv_04_15 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_macv_04_18 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_macv_04_20 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_macv_04_21 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_macv_05_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_macv_05_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_macv_05_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_macv_05_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_macv_05_08 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_macv_05_15 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_macv_05_18 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_macv_06_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_macv_06_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_macv_06_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_macv_06_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_macv_06_08 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_macv_06_15 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_macv_06_18 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_nz_01_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_nz_02_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_nz_03_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_nz_04_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_nz_05_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_nz_06_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_sas_01_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_sas_02_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_sas_03_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_seal_01_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_seal_01_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_seal_01_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_seal_01_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_seal_01_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_seal_02_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_seal_02_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_seal_02_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_seal_02_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_seal_02_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_seal_03_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_seal_04_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_seal_05_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_seal_05_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_seal_05_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_seal_05_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_seal_05_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_seal_06_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_seal_06_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_seal_06_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_seal_06_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_seal_06_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_seal_07_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_seal_07_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_seal_07_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_seal_07_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_seal_08_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_seal_08_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_seal_08_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_seal_08_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_seal_09_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_sog_01_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_sog_01_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_sog_01_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_sog_01_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_b_uniform_sog_01_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_uniform_sog_01_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 30;};
class vn_b_uniform_sog_02_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_uniform_sog_02_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 40;};
class vn_b_uniform_sog_02_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_uniform_sog_02_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 10;};
class vn_b_uniform_sog_02_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_uniform_sog_02_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 20;};
class vn_o_uniform_nva_air_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_nva_army_01_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_nva_army_01_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_nva_army_01_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_nva_army_01_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_nva_army_02_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_nva_army_02_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_nva_army_02_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_nva_army_02_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_nva_army_03_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_nva_army_03_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_nva_army_03_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 1;};
class vn_o_uniform_nva_army_03_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_nva_army_04_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_nva_army_04_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_nva_army_04_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_nva_army_04_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_nva_army_05_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_nva_army_05_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_nva_army_06_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_nva_army_06_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_nva_army_07_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_nva_army_07_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_nva_army_08_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_nva_army_08_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_nva_army_09_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_nva_army_09_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_nva_army_09_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_nva_army_09_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_nva_army_10_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_nva_army_10_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_nva_army_11_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_nva_army_11_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_nva_army_12_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_nva_army_12_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_nva_army_12_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_nva_army_12_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_nva_dc_13_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_nva_dc_13_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_nva_dc_13_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_nva_dc_13_08 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_nva_dc_14_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_nva_dc_14_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_nva_navy_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_nva_navy_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_nva_navy_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_nva_navy_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_pl_army_01_11 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_pl_army_01_12 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_pl_army_01_13 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_pl_army_01_14 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_pl_army_02_11 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_pl_army_02_12 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_pl_army_02_13 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_pl_army_02_14 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_pl_army_03_11 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_pl_army_03_12 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_pl_army_03_13 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_pl_army_03_14 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_pl_army_04_11 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_pl_army_04_12 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_pl_army_04_13 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_pl_army_04_14 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_vc_01_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_vc_01_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_vc_01_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_vc_01_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_vc_01_05 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_vc_01_06 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_vc_01_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_vc_02_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_vc_02_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_vc_02_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_vc_02_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_vc_02_05 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_vc_02_06 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_vc_02_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_vc_03_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_vc_03_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_vc_03_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_vc_03_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_vc_03_05 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_vc_03_06 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_vc_03_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_vc_04_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_vc_04_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_vc_04_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_vc_04_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_vc_04_05 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_vc_04_06 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_vc_04_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_vc_05_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_vc_05_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_vc_05_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_vc_05_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_vc_mf_01_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_vc_mf_02_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_vc_mf_03_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_vc_mf_04_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_vc_mf_09_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_vc_mf_10_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_uniform_vc_mf_11_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 30;};
class vn_o_uniform_vc_mf_12_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_uniform_vc_reg_11_08 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 40;};
class vn_o_uniform_vc_reg_11_09 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_uniform_vc_reg_11_10 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 10;};
class vn_o_uniform_vc_reg_12_08 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_uniform_vc_reg_12_09 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 20;};
class vn_o_uniform_vc_reg_12_10 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_b_vest_aircrew_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_aircrew_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_vest_aircrew_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_vest_aircrew_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_vest_aircrew_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_vest_aircrew_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_aircrew_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_vest_anzac_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_vest_anzac_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_vest_anzac_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_vest_anzac_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_anzac_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_vest_anzac_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_vest_anzac_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_vest_anzac_08 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_vest_anzac_09 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_anzac_10 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_vest_sas_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_vest_sas_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_vest_sas_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_vest_sas_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_seal_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_vest_seal_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_vest_seal_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_vest_seal_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_vest_seal_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_seal_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_vest_seal_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_vest_sog_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_vest_sog_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_vest_sog_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_sog_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 1;};
class vn_b_vest_sog_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_vest_sog_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_vest_usarmy_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_vest_usarmy_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_usarmy_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_vest_usarmy_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_vest_usarmy_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_vest_usarmy_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_vest_usarmy_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_usarmy_08 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_vest_usarmy_09 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_vest_usarmy_10 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_vest_usarmy_11 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_vest_usarmy_12 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_usarmy_13 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_vest_usarmy_14 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_vest_usmc_01 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_vest_usmc_02 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_vest_usmc_03 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_usmc_04 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_b_vest_usmc_05 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 25;};
class vn_b_vest_usmc_06 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 35;};
class vn_b_vest_usmc_07 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 45;};
class vn_b_vest_usmc_08 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 5;};
class vn_b_vest_usmc_09 {allowedSides[] = {"WEST"}; appearanceSide = "WEST"; minLevel = 15;};
class vn_o_vest_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 1;};
class vn_o_vest_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_vest_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_vest_05 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_vest_06 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 45;};
class vn_o_vest_07 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_vest_08 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
class vn_o_vest_vc_01 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 25;};
class vn_o_vest_vc_02 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 35;};
class vn_o_vest_vc_03 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 45;};
class vn_o_vest_vc_04 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 5;};
class vn_o_vest_vc_05 {allowedSides[] = {"EAST"}; appearanceSide = "EAST"; minLevel = 15;};
